[project]
name = "pyright-cov"
version = "0.1.0"
description = "Run PyRight and enforce minimum type coverage"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
pyright-cov = "pyright_cov:main"

